import { useEffect, useState } from "react";
export default function BaseOptionsTable({title,endpoint}){
 const [items,setItems]=useState([]),[value,setValue]=useState(""),[edit,setEdit]=useState(null),[selected,setSelected]=useState(new Set()),[delOpen,setDelOpen]=useState(false);
 const api=async(o={})=>{const r=await fetch(endpoint,{credentials:"include",...o,headers:{"Content-Type":"application/json"}}),d=await r.json();if(!r.ok)throw Error(d.error);return d};
 useEffect(()=>{api().then(d=>setItems(d.items||[]))},[endpoint]);
 const add=async e=>{e.preventDefault();if(!value)return;const d=await api({method:"POST",body:JSON.stringify({title:value})});setItems(x=>[...x,d.item]);setValue("")};
 const save=async e=>{e.preventDefault();const d=await api({method:"PATCH",body:JSON.stringify({id:edit.id,title:value})});setItems(x=>x.map(i=>i.id===d.item.id?d.item:i));setEdit(null);setValue("")};
 const remove=async()=>{await api({method:"DELETE",body:JSON.stringify({ids:[...selected]})});setItems(x=>x.filter(i=>!selected.has(String(i.id))));setSelected(new Set());setDelOpen(false)};
 return <section className="rounded-2xl border border-black/10 bg-white p-4"><h2 className="mb-4 font-bold">{title}</h2><form onSubmit={add} className="grid grid-cols-[1fr_auto] gap-3"><input className="h-10 rounded-2xl border px-3" value={value} onChange={e=>setValue(e.target.value)}/><button className="h-10 w-10 rounded-xl border"><img src="/images/icons/afzodan.svg"/></button></form><table className="mt-4 w-full"><thead><tr className="bg-neutral-200"><th><input type="checkbox"/></th><th>#</th><th>عنوان</th><th>عملیات</th></tr></thead><tbody>{items.map((i,n)=><tr key={i.id}><td><input type="checkbox" onChange={()=>setSelected(s=>new Set(s).add(String(i.id)))}/></td><td>{n+1}</td><td>{i.title}</td><td><button onClick={()=>{setEdit(i);setValue(i.title)}}>ویرایش</button></td></tr>)}</tbody></table><button onClick={()=>setDelOpen(true)}>حذف</button>{edit&&<div className="fixed inset-0 z-[10000] grid place-items-center bg-black/40"><form onSubmit={save} className="rounded-2xl bg-white p-5"><input value={value} onChange={e=>setValue(e.target.value)}/><button>ذخیره</button><button type="button" onClick={()=>setEdit(null)}>انصراف</button></form></div>}{delOpen&&<div className="fixed inset-0 z-[10000] grid place-items-center bg-black/40"><div className="rounded-2xl bg-white p-5"><p>حذف شود؟</p><button onClick={remove}>حذف</button><button onClick={()=>setDelOpen(false)}>انصراف</button></div></div>}</section>
}
